### ISSUE TITLE
Unable to Load various Chinese Levels

### ISSUE THREAD

**Issue by capSAR273** [doyaGu/BallanceModLoaderPlus#1]
Hello,

I just updated my BMLP to 0.3.0 (thank you for the update!), and am still unable to load various levels I saved from the Chinese community. I changed the level filenames to english characters just to be safe. Here is one log example, but any time the game hangs loading the level each log looks the same like this: 
[ModLoader.log](https://github.com/user-attachments/files/15866318/ModLoader.log)

It spams that last info line until I close Ballance, the progress bar does fully make it across as well while loading the level. I can upload the map files to somewhere if you need to test them specifically. I'm not sure if its a BMLP bug or the levels might not be compatible with the new Ballance player.

**Comment by doyaGu** [comment]
Thank you for reporting this issue. The problem is due to a broken version of the "Segment" mod in the ModLoader/Mods directory. Removing this mod should resolve the issue. I have updated the release package to address this problem. If you encounter any further issues, please let me know.
